<?php

/**
 * @file _init.php
 * @author giorno
 * @package N7
 * @license Apache License, Version 2.0, see LICENSE file
 *
 * Initialization of N7 solution basic configuration. Do not edit this file.
 */

error_reporting( E_ALL );

/**
 * Configuring solution specific root paths.
 */
define( 'N7_SOLUTION_ROOT', dirname( __FILE__ ) . '/' );
define( 'N7_SOLUTION_LIB',	N7_SOLUTION_ROOT . 'lib/' );
define( 'N7_SOLUTION_APPS',	N7_SOLUTION_ROOT . 'apps/' );

/**
 * Serverware version.
 */
define( 'N7_SOLUTION_VERSION', '0.1-beta' );

/**
 * Loading installation specific configuration.
 */
require_once N7_SOLUTION_ROOT . '_cfg.php';

/**
 * Loading other required resources.
 */
require_once N7_FRAMEWORK_ROOT . '/cfg/config.php';

/**
 * Setup Smarty wrapper defaults.
 */
require_once CHASSIS_LIB . 'ui/_smarty_wrapper.php';
_smarty_wrapper::getInstance( )->setDir( N7_SOLUTION_ROOT . 'smarty/templates' );
_smarty_wrapper::getInstance( )->setContent( 'index.html' );
$__SMARTY = _smarty_wrapper::getInstance( )->getEngine( );

?>